/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zsv_ZsvNative */

#ifndef _Included_zsv_ZsvNative
#define _Included_zsv_ZsvNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zsv_ZsvNative
 * Method:    createParserFromPath
 * Signature: (Ljava/lang/String;C)J
 */
JNIEXPORT jlong JNICALL Java_zsv_ZsvNative_createParserFromPath
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     zsv_ZsvNative
 * Method:    createParserFromString
 * Signature: (Ljava/lang/String;C)J
 */
JNIEXPORT jlong JNICALL Java_zsv_ZsvNative_createParserFromString
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     zsv_ZsvNative
 * Method:    parseNextRow
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_zsv_ZsvNative_parseNextRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     zsv_ZsvNative
 * Method:    closeParser
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_zsv_ZsvNative_closeParser
  (JNIEnv *, jclass, jlong);

/*
 * Class:     zsv_ZsvNative
 * Method:    rewindParser
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_zsv_ZsvNative_rewindParser
  (JNIEnv *, jclass, jlong);

/*
 * Class:     zsv_ZsvNative
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zsv_ZsvNative_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
